#!/usr/bin/env node
// Fetches box art and basic metadata from IGDB into data/meta.js:
//
//   c  cover image id: https://images.igdb.com/igdb/image/upload/t_cover_big/<c>.jpg
//   g  genres
//   d  developer(s)
//   s  summary, cut to a couple of sentences
//
// Uses each game's IGDB entry from data/scores.js, so it needs the same Twitch
// credentials in .env.local as tools/fetch-scores.js. Two requests in all.
//
//   node tools/fetch-meta.js && node build.js

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const rel = p => path.join(ROOT, p);

try { process.loadEnvFile(rel(".env.local")); } catch (e) { /* fall back to the real environment */ }
const { TWITCH_CLIENT_ID: ID, TWITCH_CLIENT_SECRET: SECRET, TWITCH_ACCESS_TOKEN: TOKEN } = process.env;
if (!ID || !(SECRET || TOKEN)) {
  console.error("Set TWITCH_CLIENT_ID and TWITCH_CLIENT_SECRET in .env.local.");
  process.exit(1);
}

global.window = {};
require(rel("data/games.js"));
require(rel("data/scores.js"));
const GAMES = window.GAMES, SCORES = window.SCORES;
const keyOf = g => g[0] + "|" + g[1];

// the first sentences that fit in about 240 characters: enough to say what the game is
function shorten(s){
  if (!s) return undefined;
  s = s.replace(/\s+/g, " ").trim();
  if (s.length <= 240) return s;
  const sentences = s.match(/[^.!?]+[.!?]+(\s|$)/g) || [s];
  let out = "";
  for (const x of sentences) { if ((out + x).length > 240) break; out += x; }
  return (out || s.slice(0, 237).replace(/\s\S*$/, "") + "…").trim();
}

(async () => {
  const tok = TOKEN || (await (await fetch("https://id.twitch.tv/oauth2/token?client_id=" + encodeURIComponent(ID) +
    "&client_secret=" + encodeURIComponent(SECRET) + "&grant_type=client_credentials", { method: "POST" })).json()).access_token;

  const slugs = [...new Set(Object.values(SCORES).map(s => s.id))];
  const bySlug = {};
  for (let i = 0; i < slugs.length; i += 400) {
    const r = await fetch("https://api.igdb.com/v4/games", {
      method: "POST",
      headers: { "Client-ID": ID, "Authorization": "Bearer " + tok },
      body: "fields slug,summary,cover.image_id,genres.name,involved_companies.developer,involved_companies.company.name; " +
        "where slug = (" + slugs.slice(i, i + 400).map(s => JSON.stringify(s)).join(",") + "); limit 500;",
    });
    if (!r.ok) throw new Error("IGDB failed: " + r.status + " " + await r.text());
    for (const g of await r.json()) bySlug[g.slug] = g;
    await new Promise(r => setTimeout(r, 300));
  }

  const out = {};
  for (const g of GAMES) {
    const s = SCORES[keyOf(g)], m = s && bySlug[s.id];
    if (!m) continue;
    const rec = {};
    if (m.cover && m.cover.image_id) rec.c = m.cover.image_id;
    if (m.genres) rec.g = m.genres.map(x => x.name).slice(0, 3);
    const devs = (m.involved_companies || []).filter(c => c.developer && c.company).map(c => c.company.name);
    if (devs.length) rec.d = [...new Set(devs)].slice(0, 2);
    const sum = shorten(m.summary);
    if (sum) rec.s = sum;
    out[keyOf(g)] = rec;
  }

  const sorted = Object.fromEntries(Object.entries(out).sort(([a], [b]) => a.localeCompare(b)));
  fs.writeFileSync(rel("data/meta.js"),
    "// Box art and metadata from IGDB, keyed year|title. Generated by tools/fetch-meta.js - don't edit by hand.\n" +
    "// {c: cover image id, g: genres, d: developers, s: summary}\n" +
    "window.META = " + JSON.stringify(sorted).replace(/\},"/g, '},\n"') + ";\n", "utf8");
  const n = Object.values(out);
  console.log(n.length + " games: " + n.filter(x => x.c).length + " covers, " + n.filter(x => x.s).length +
    " summaries. " + (fs.statSync(rel("data/meta.js")).size / 1024).toFixed(0) + " KB. Run node build.js next.");
})().catch(e => { console.error(e.message || e); process.exit(1); });
